config/routes.rb
Smokers::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :places, :only => [:show] do
    resources :reviews
  end
  resources :categories, :only => [:show]
  resources :cities, :only => [:show]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'contact', to: 'contact#deliver_mail', as: 'contact', :via => :post

  resources :users
  resources :sessions
  resources :ratings, only: :update
  get "about" => "static_pages#about"
  
  
  get "news" => "static_pages#news"
  get "events" => "static_pages#events"
  scope "(:locale)", :locale => /en|he/ do
    resources :cities, :only => [:show]

    resources :places, :only => [:show] do
      resources :reviews
    end
    root :to => 'homepage#homepage'

    get 'homepage' => 'homepage#homepage'
    get 'show_selected'=> 'homepage#show_selected', :via => :post
    get 'contact' => 'contact#contact', :via => :post
    get 'deliver_mail' => 'contact#deliver_mail', :via => :post
  end

end

app/views/shared/_contact_form.html.erb
<% if I18n.locale == :en %>
<!-- Modal -->
<div class="modal fade" id="contact" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					&times;
				</button>
				<h4 class="modal-title" id="myModalLabel">Hi! contact us</h4>
			</div>
			<div class="modal-body">
					<%= form_tag url_for(:action => 'deliver_mail', :controller => 'contact'), :method => 'get' do %>
				<div class="form-group">
					<%= text_area_tag 'message','', :class => "form-control", placeholder:  "Message"  %>
				</div>
				<div class="form-group">
					<%= email_field_tag 'address','', :class => "form-control", placeholder: "Email address" %>
				</div>
				<div class="form-group">
					<%= text_field_tag 'name', '', :class => "form-control", placeholder: "Name" %>
				</div>

			</div>
			<div class="modal-footer">

				<%= submit_tag "Send" , :class=> "btn btn-warning" %>
				<% end %>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<% end %>
<% if I18n.locale == :he %>
<!-- Modal -->
<div class="modal fade" id="h-contact" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					&times;
				</button>
				<h4 class="modal-title h-form" id="myModalLabel">צרו קשר</h4>
			</div>
			<div class="modal-body">
					<%= form_tag url_for(:action => 'deliver_mail', :controller => 'contact'), :method => 'get' do %>
				<div class="form-group">
					<%= text_area_tag 'message','', :class => "form-control h-form", placeholder:  t('Message')  %>
				</div>
				<div class="form-group">
					<%= email_field_tag 'address','', :class => "form-control h-form", placeholder: t('Email') %>
				</div>
				<div class="form-group">
					<%= text_field_tag 'name', '', :class => "form-control h-form", placeholder: t('Name') %>
				</div>

			</div>
			<div class="modal-footer">

				<%= submit_tag t('Send') , :class=> "btn btn-warning h-form" %>
				<% end %>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<% end %>

app/views/shared/_log_in_form.html.erb
<% if I18n.locale == :en %>
	<!-- Modal -->
	<div class="modal fade" id="log-in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Log in</h4>
				</div>
				<div class="modal-body">
					<%= form_tag sessions_path do %>
						<div class="field">
							<%= text_field_tag :email, params[:email], :class => "form-control", placeholder: 'email' %>
						</div>
						<div class="field">
							<%= password_field_tag :password, '', :class => "form-control", placeholder: 'password'  %>
						</div>
						<div class="modal-footer">
							<%= submit_tag 'log in', :class=> "btn btn-warning" %>		
					<% end %>
						</div>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
<% end %>	
<% if I18n.locale == :he %>
	<!-- Modal -->
	<div class="modal fade" id="h-log-in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title h-form" id="myModalLabel">כניסה</h4>
				</div>
				<div class="modal-body">
					<%= form_tag sessions_path do %>
						<div class="field">
							<%= text_field_tag :email, params[:email], :class => "form-control h-form", placeholder: t('Email') %>
						</div>
						<div class="field">
							<%= password_field_tag :password, '', :class => "form-control h-form", placeholder: t('Password')  %>
						</div>
						<div class="modal-footer">
							<%= submit_tag t('Log in'), :class=> "btn btn-warning h-form" %>		
					<% end %>
						</div>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
<% end %>	

app/views/shared/_recommend_form.html.erb
<% if I18n.locale == :en %>
	<!-- Eng Modal -->
	<div class="modal fade" id="recommend" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<% if current_user %>
					<h4 class="modal-title" id="myModalLabel">Hi <%= current_user.email %>, know of a smoke-free place which is not on the list? Let us know!</h4>
					<% end %>
					
				</div>
				<div class="modal-body">
	
					<%= form_tag url_for(:action => 'deliver_mail',  :controller => 'contact'), :method => 'get' do %>
					
					<% if current_user %>
					<%= hidden_field_tag(:address, current_user.email) %>
					<% end %>
					<div class="form-group">
						<%= text_field_tag 'place_name', '', :class => "form-control", placeholder: "place Name"   %>
					</div>
					<div class="form-group">
						<%= text_field_tag 'place_address', '', :class => "form-control", placeholder: "place address"   %>
					</div>
					<div class="form-group">
	
						<%= text_area_tag 'message','', :class => "form-control", placeholder: "additional details"   %>
					</div>
				</div>
				<div class="modal-footer">
					<%= submit_tag "Send" , :class=> "btn btn-warning" %>
					<% end %>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.english modal -->
<% end %>

<% if I18n.locale == :he %>
	<!-- Hebrew Modal -->
	<div class="modal fade" id="h-recommend" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<% if current_user %>
					<h4 class="modal-title h-form" id="myModalLabel"> <%= current_user.email %> היי</h4>
					<% end %>
					
				</div>
				<div class="modal-body">
	
					<%= form_tag url_for(:action => 'deliver_mail',  :controller => 'contact'), :method => 'get' do %>
					
					<% if current_user %>
					<%= hidden_field_tag(:address, current_user.email) %>
					<% end %>
					<div class="form-group">
						<%= text_field_tag 'place_name', '', :class => "form-control h-form", placeholder: "שם המקום"   %>
					</div>
					<div class="form-group">
						<%= text_field_tag 'place_address', '', :class => "form-control h-form", placeholder: "כתובת"   %>
					</div>
					<div class="form-group">
	
						<%= text_area_tag 'message','', :class => "form-control h-form", placeholder: "פרטים נוספים "   %>
					</div>
				</div>
				<div class="modal-footer">
					<%= submit_tag t('Send') , :class=> "btn btn-warning h-form" %>
					<% end %>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.hebrew modal -->
<% end %>

app/views/shared/_sign_up_form.html.erb
<% if I18n.locale == :en %> <!-- Modal -->
	<div class="modal fade" id="sign-up" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Sign up to rate and recommend new places</h4>
				</div>
				<div class="modal-body">
					<%= form_for @user do |f| %>
					<% if @user.errors.any? %>
					<div class="error_messages">
						<h2>Form is invalid</h2>
						<ul>
							<% @user.errors.full_messages.each do |message| %>
							<li>
								<%= message %>
							</li>
							<% end %>
						</ul>
					</div>
					<% end %>
					<div class="field">
						<%= f.text_field :email, :class => "form-control", :placeholder => 'email' %>
					</div>
					<div class="field">
						<%= f.password_field :password, :class => "form-control", :placeholder => "password" %>
					</div>
					<div class="field">
						<%= f.password_field :password_confirmation, :class => "form-control", :placeholder => "password confirmation" %>
					</div>
				</div>
				<div class="modal-footer">
					<%= f.submit "Sign Up", :class=> "btn btn-warning" %>
					<% end %>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
<%end%>


<% if I18n.locale == :he %> <!-- Modal -->
	<div class="modal fade" id="h-sign-up" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title h-form" id="myModalLabel">הרשמו כדי להמליץ ולדרג מקומות</h4>
				</div>
				<div class="modal-body">
					<%= form_for @user do |f| %>
					<% if @user.errors.any? %>
					<div class="error_messages">
						<h2>Form is invalid</h2>
						<ul>
							<% @user.errors.full_messages.each do |message| %>
							<li>
								<%= message %>
							</li>
							<% end %>
						</ul>
					</div>
					<% end %>
					<div class="field">
						<%= f.text_field :email, :class => "form-control h-form", :placeholder => t('Email') %>
					</div>
					<div class="field">
						<%= f.password_field :password, :class => "form-control h-form", :placeholder => t('Password') %>
					</div>
					<div class="field">
						<%= f.password_field :password_confirmation, :class => "form-control h-form", :placeholder => t('Password confirmation') %>
					</div>
				</div>
				<div class="modal-footer">
					<%= f.submit t('Sign up'), :class=> "btn btn-warning h-form" %>
					<% end %>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
<%end%>