config/routes.rb
Smokers::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :places, :only => [:show] do
    resources :reviews
  end
  resources :categories, :only => [:show]
  resources :cities, :only => [:show]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'contact', to: 'contact#deliver_mail', as: 'contact', :via => :post

  resources :users
  resources :sessions
  resources :ratings, only: :update
  get "about" => "static_pages#about"
  
  
  get "news" => "static_pages#news"
  get "events" => "static_pages#events"
  scope "(:locale)", :locale => /en|he/ do
    resources :cities, :only => [:show]

    resources :places, :only => [:show] do
      resources :reviews
    end
    root :to => 'homepage#homepage'

    get 'homepage' => 'homepage#homepage'
    get 'show_selected'=> 'homepage#show_selected', :via => :post
    get 'contact' => 'contact#contact', :via => :post
    get 'deliver_mail' => 'contact#deliver_mail', :via => :post
  end

end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :places
  def to_param
    name
  end

  def location
  
    location_lat=places.map(& :latitude).inject{ |sum, el| sum + el }.to_f / places.size
    location_longitude=places.map(& :longitude).inject{ |sum, el| sum + el }.to_f / places.size
    return [location_lat,location_longitude]
  end
  
  def self.make_name_array
    names = City.pluck(:name)
    arr = Array.new
    names.each {|n| arr << [n.gsub('-', ' '),n] }
    return arr
  end  
  
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
   
    @city = City.where(:name => params["id"]).first
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render action: 'show', status: :created, location: @city }
      else
        format.html { render action: 'new' }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      #raise params.to_s
      @city = City.where(:name => params["id"]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :h_name)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <!--><h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>
-->
      <h2><%= t 'activerecord.errors.template.header', :model => City.model_name.human, :count => @city.errors.count %></h2>

      <ul>
      <% @city.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :h_name %><br>
    <%= f.text_field :h_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<!--<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>
-->
<h1><%= t 'views.city.edit.title' %></h1>

<%= render 'form' %>

<%= link_to I18n.t('views.show'), @city %> |
<%= link_to I18n.t('views.back'), cities_path %>

app/views/cities/index.html.erb
<h1><%= t 'views.city.index.listing_cities' %></h1>

<table>
  <tr>
    <th><%= City.human_attribute_name(:name) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cities.each do |city| %>
  <tr>
    <td><%= city.name %></td>
    <td><%= link_to I18n.t('views.show'), city %></td>
    <td><%= link_to I18n.t('views.edit'), edit_city_path(city) %></td>
    <td><%= link_to I18n.t('views.destroy'), city, confirm: I18n.t('views.are_you_sure'), method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to I18n.t('views.city.index.new_city'), new_city_path %>

app/views/cities/new.html.erb
<h1><%= t 'views.city.new.name' %></h1>

<%= render 'form' %>

<%= link_to I18n.t('views.back'), cities_path %>

app/views/cities/show.html.erb
<% @places = Place.where(:city_id => @city.id) %>
<% places_sorted = @places.sort_by{ |name| name[:name] } %>
<div id="city-container">
	<% if I18n.locale == :en %>
	
		<div id="places-column">
			<div class="places-count">
				<% if @places.count == 1%>
					<%= @places.count %> Bar in <%= @city.name.gsub('-',' ') %> Area
				<%else%>
					<%= @places.count %> Bars in <%= @city.name.gsub('-',' ') %> Area

				<%end%>
			</div>
			</br>
			<% places_sorted.each do |place| %>
				<div class="well bar-container">
					<div class="bar-name-list">
						<%= link_to "#{place.name.gsub('-',' ')}", place %>
					</div>	
					<p>
						<%= place.categories.map(&:name).join(', ') %>
					</p>
					<p>
						<%= place.address %>
					</p>
					<p>
						<%= place.details %>
					</p>
					<% id = 'star' +  place.id.to_s %>
					<div id="<%= id %>"></div>
					
					<% content_for :scripts do %>
						<script>$(document).ready(rateplaces( "<%= id %>",<%= place.average_rating %>));</script>
					<% end %>
					
				</div> <!--bar-container-->
			<%end%><!--places loop-->
		</div><!--places_column-->
		
	<%end%><!--English -->
	
	<% if I18n.locale == :he %>
		<div id="h-places-column">
			<div class="h-places-count places-count">
				<% if @places.count == 1%>
					<%= t('1 bar in area') %>  <%= @city.h_name.gsub('-',' ')%>
				<%else%>
				  <%= @places.count %> <%= t('bars in area') %>  <%= @city.h_name.gsub('-',' ')%>
 				
				<%end%>
			</div>
			</br>
			<% places_sorted.each do |place| %>
				
				<div class="well bar-container">
					<div class="bar-name-list">
						<% place_url = "/he/places/" + place.id.to_s %>
						<a href="<%= place_url %>"><%= place.h_name.gsub('-',' ')%></a>
					</div>	
					<p>
						<%= place.categories.map(&:h_name).join(', ') %>
					</p>
					<p>
						<%= place.h_address %>
					</p>
					<p>
						<%= place.h_details %>
					</p>
					
					<% id = 'star' +  place.id.to_s %>
					<div id="<%= id %>"></div>

					<% content_for :scripts do %>
						<script>$(document).ready(rateplaces( "<%= id %>",<%= place.average_rating %>));</script>
					<% end %>
					
				</div> <!--bar-container-->
			<%end%><!--places loop-->
		</div><!--places_column-->
	<%end%><!--Hebrew -->

	<div id="map-canvas" data-center="<%= @city.location.to_json%>" data-places= "<%= @places.to_json %>"></div>

</div>

app/views/cities/tests.html.erb
<p id="bla1">bla1</p>
<p id="bla2">bla2</p>