config/routes.rb
Smokers::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :places, :only => [:show] do
    resources :reviews
  end
  resources :categories, :only => [:show]
  resources :cities, :only => [:show]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'contact', to: 'contact#deliver_mail', as: 'contact', :via => :post

  resources :users
  resources :sessions
  resources :ratings, only: :update
  get "about" => "static_pages#about"
  
  
  get "news" => "static_pages#news"
  get "events" => "static_pages#events"
  scope "(:locale)", :locale => /en|he/ do
    resources :cities, :only => [:show]

    resources :places, :only => [:show] do
      resources :reviews
    end
    root :to => 'homepage#homepage'

    get 'homepage' => 'homepage#homepage'
    get 'show_selected'=> 'homepage#show_selected', :via => :post
    get 'contact' => 'contact#contact', :via => :post
    get 'deliver_mail' => 'contact#deliver_mail', :via => :post
  end

end

app/models/place.rb
class Place < ActiveRecord::Base
  
  belongs_to :city
  has_and_belongs_to_many :categories
  has_many :reviews
  geocoded_by :address
  after_validation :geocode
  has_many :ratings
  def average_rating
    if ratings.size==0
    return 0

    else
      r = (ratings.sum(:score).to_f / ratings.size).round
    end
    #raise r.to_s
  end
  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
    if current_user
      if Rating.where(place_id: @place.id, user_id: current_user.id).first
        @rating = Rating.where(place_id: @place.id, user_id: @current_user.id).first
      else
        @rating = Rating.create(place_id: @place.id, user_id: current_user.id, score: 0)
      end
    end
  end

  # GET /places/new
  def new
    @place = Place.new

  end

  # GET /places/1/edit
  def edit

  end

  # POST /places
  # POST /places.json
  def create
    id = City.where(:name =>params['city_name']).first.id
    params['place']['city_id']=id

    @place = Place.new(place_params)
    categories = Category.where(:name=> params.keys)
    @place.categories = categories
    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render action: 'show', status: :created, location: @place }
      else
        format.html { render action: 'new' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update

    categories = Category.where(:name=> params.keys)

    id = City.where(:name =>params['city_name']).first.id
    params['place']['city_id']=id
    @place.categories = categories
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_place
    @place = Place.find(params[:id])
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def place_params
    params.require(:place).permit(:city_name, :name, :city_id,  :category_id, :h_name, :address, :h_address, :h_details, :details,  :latitude, :longitude, :website)
  end

  def review_params
    params.require(:review).permit(:content, :name, :rating, :place_id, :authenticity_token, :commit)
  end
end

app/helpers/places_helper.rb
module PlacesHelper
  

    def url_with_protocol(url)
    /^http/.match(url) ? url : "http://#{url}"
    end

end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
     <!-- <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>-->
		<h2><%= t 'activerecord.errors.template.header', :model => Place.model_name.human, :count => @place.errors.count %></h2>
      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  
  <div class="field">
    <%= f.label :h_name %><br>
    <%= f.text_field :h_name %>
  </div>
  <div class="field">
    <%= f.label :h_address %><br>
    <%= f.text_field :h_address %>
  </div>
  <div class="field">
    <%= f.label :h_details %><br>
    <%= f.text_area :h_details %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <%= select_tag(:city_name, options_for_select(City.pluck(:name))) %> 
  
  
 <% Category.all.each do |category| %>
 <div>
 <label><%= category.name%></label>	
 <%= check_box_tag(category.name, value='1')%>
</div>
<% end %>

<div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<!--<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>
-->

<h1><%= t 'views.place.edit.title' %></h1>

<%= render 'form' %>

<%= link_to I18n.t('views.show'), @place %> |
<%= link_to I18n.t('views.back'), places_path %>

app/views/places/index.html.erb
<h1>Listing places</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Category</th>
      <th>Name</th>
      <th>Address</th>
      <th>Details</th>
      <th>h_Name</th>
      <th>h_Address</th>
      <th>h_Details</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Website</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.city_id %></td>
        <td><%= place.categories.map(&:name).join(', ') %></td>
        <td><%= place.name %></td>
        <td><%= place.address %></td>
        <td><%= place.details %></td>
        <td><%= place.h_name %></td>
        <td><%= place.h_address %></td>
        <td><%= place.h_details %></td>
        <td><%= place.latitude %></td>
        <td><%= place.longitude %></td>
        <td><%= place.website %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1><%= t 'views.place.new.name' %></h1>

<%= render 'form' %>

<%= link_to I18n.t('views.back'), places_path %>

app/views/places/show.html.erb
<div id="city-container">
<div id="map-canvas" data-name="<%= @place.name.to_json%>" data-h-name="<%= @place.h_name.to_json%>" data-website="<%= @place.website.to_json%>" data-lat="<%= @place.latitude.to_json%>" data-lng="<%= @place.longitude.to_json%>"
data-address= "<%= @place.address.to_json %>" data-h-address= "<%= @place.h_address.to_json %>"
></div>



<% if I18n.locale == :en %>
	<div class="well" id="place-column" >
	
		
			<div class="bar-name">
				<%= @place.name.gsub('-',' ') %>
			</div>
			
			<div>	
				<%= @place.categories.map(&:name).join(', ') %>
			</div>
			<div id="address">
				<%= @place.address %>
			</div>
			<div id="details">some more details here
				<%= @place.details %>
			</div>
			<% unless @place.website.blank? %>
				<div class="website">
					<%= link_to @place.website,url_with_protocol(@place.website), :target => '_blank'%>	
					
				</div>	
			<%end%>
			<div>
				<%= t('Average rating') %>	
				<div id="star"></div>
			</div>
			<div>
				<% if current_user %>
					<%= t('Rate this place') %>
				<%else%>
					<%= t('Log in to rate') %>
				<%end%>
					<div id="user_star"></div>
			</div>
		
	    <div>
	    	<strong style="font-size: 20px;">Get directions from your location</strong></br>
			<strong>Mode of Travel: </strong>
				<select id="mode" onchange="calcRoute();">
				  <option value="DRIVING">Driving</option>
				  <option value="WALKING">Walking</option>
				  <option value="BICYCLING">Bicycling</option>
				  <option value="TRANSIT">Transit</option>
				</select>
		</div>
		<div id="nearby-places-box" >
			<div id="nearby-places">Nearby Places</div>
			<ul>
				<%for place in @place.nearbys(0.5)%>
					<li>
						<%= link_to place.name.gsub('-',' '), place%> (<%= (place.distance * 1609.34).round(2)%> m)
					</li>
				<%end%>
			</ul>
		
		</div>
		

	<% string = "http://noSmokingPlaces.com/" + @place.id.to_s + "/comments" %>
	
	<div class="fb-comments" data-href=<%= string %> data-numposts="5" data-colorscheme="light"></div>
		



<script>
jQuery(document).ready(rateplaces("star", <%= @place.average_rating %>));</script>

<% if @rating %>
<script>
		jQuery(document).ready(function(){
			$('#user_star').raty({
				start: <%= @rating.score %>,
				path: '/assets',
				click: function(score, evt) {
					$.ajax({
						url: '/ratings/' + <%= @rating.id %>,
						type: 'PATCH',
						data: { score:score,place_id: <%= @place.id %>
								}
							});
				}
			});
		});
</script>
<% end %>
</div>




<%end%>



<% if I18n.locale == :he %>
	<div class="well" id="h-place-column" >
		
			<div id="h-bar-name">
				<%= @place.h_name.gsub('-',' ') %>
			</div>
			<div>	
				<%= @place.categories.map(&:h_name).join(', ') %>
			</div>
			<div id="h-address">
				<%= @place.h_address %>
			</div>
			<div id="h-details">
				כל מיני פרטים נוספים כאן
				<%= @place.h_details %>
			</div>
			<% unless @place.website.blank? %>
				<div class="website">
					<%= link_to @place.website,url_with_protocol(@place.website), :target => '_blank'%>	
					
				</div>	
			<%end%>
			<div>
				<%= t('Average rating') %>	
				<div id="star"></div>
			</div>
			<div>
				<% if current_user %>
					<%= t('Rate this place') %>
				<%else%>
					<%= t('Log in to rate') %>
				<%end%>
					<div class="h-star" id="user_star"></div>
			</div>
		
	    <div>
			<strong>Mode of Travel: </strong>
				<select id="mode" onchange="calcRoute();">
				  <option value="DRIVING">Driving</option>
				  <option value="WALKING">Walking</option>
				  <option value="BICYCLING">Bicycling</option>
				  <option value="TRANSIT">Transit</option>
				</select>
		</div>
		<div id= "h-nearby-places-box">
			<div id= "h-nearby-places">  מקומות בילוי באזור  
			</div>	
			<ul>
				<%for place in @place.nearbys(0.5)%>
					<li>
						<% place_url = "/he/places/" + place.id.to_s %>
							<a href="<%= place_url %>"><%= place.h_name.gsub('-',' ')%>(<%= (place.distance * 1609.34).round(2)%> מטרים)</a>
						
					</li>
				<%end%>
			</ul>
		
		</div>
		

	<% string = "http://noSmokingPlaces.com/" + @place.id.to_s + "/comments" %>
	
	<div class="fb-comments" data-href=<%= string %> data-numposts="5" data-colorscheme="light"></div>
		



<script>
jQuery(document).ready(rateplaces("star", <%= @place.average_rating %>));</script>

<% if @rating %>
<script>
		jQuery(document).ready(function(){
			$('#user_star').raty({
				start: <%= @rating.score %>,
				path: '/assets',
				click: function(score, evt) {
					$.ajax({
						url: '/ratings/' + <%= @rating.id %>,
						type: 'PATCH',
						data: { score:score,place_id: <%= @place.id %>
							  }
							});
						}
			});
		});
</script>
<% end %>
</div>
<%end%>

<script>jQuery(document).ready(function($) {initialize_place();});</script>
<!--script>jQuery(document).ready(function($) {calcRoute(32.0806126, 34.7738658, 31.7819054, 35.2213715);});</script-->